import MainLayout from "@/layouts/MainLayout";
import { Metadata } from "next";
import { ReactElement } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Home() {
  return <h1 className="text-red-400">this is home page</h1>;
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>;
};

export default Home;
