import Card from '@/components/Card';
import MainLayout from '@/layouts/MainLayout';
import { Metadata } from 'next';
import Image from 'next/image';
import { ReactElement } from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Blog {
  banner: string;
  title: string;
  description: string;
  createdAt: string;
}

const popularPosts: Blog[] = [
  {
    banner:
      'https://i0.wp.com/www.footballparadise.com/wp-content/uploads/2022/12/Give-it-to-Messi-and-Pray-Netherlands-vs-Argentina-Op-1-copy-1-scaled.jpg?resize=1024%2C724&ssl=1',
    title: 'I Like to Keep Things Simple to Appreciate the Details',
    description:
      'Many years ago, I worked for my parents who own a video production company.',
    createdAt: '28/06/2001',
  },
  {
    banner:
      'https://i0.wp.com/www.footballparadise.com/wp-content/uploads/2022/12/Give-it-to-Messi-and-Pray-Netherlands-vs-Argentina-Op-1-copy-1-scaled.jpg?resize=1024%2C724&ssl=1',
    title: 'I Like to Keep Things Simple to Appreciate the Details',
    description:
      'Many years ago, I worked for my parents who own a video production company.',
    createdAt: '28/06/2001',
  },
  {
    banner:
      'https://i0.wp.com/www.footballparadise.com/wp-content/uploads/2022/12/Give-it-to-Messi-and-Pray-Netherlands-vs-Argentina-Op-1-copy-1-scaled.jpg?resize=1024%2C724&ssl=1',
    title: 'I Like to Keep Things Simple to Appreciate the Details',
    description:
      'Many years ago, I worked for my parents who own a video production company.',
    createdAt: '28/06/2001',
  },
  {
    banner:
      'https://i0.wp.com/www.footballparadise.com/wp-content/uploads/2022/12/Give-it-to-Messi-and-Pray-Netherlands-vs-Argentina-Op-1-copy-1-scaled.jpg?resize=1024%2C724&ssl=1',
    title: 'I Like to Keep Things Simple to Appreciate the Details',
    description:
      'Many years ago, I worked for my parents who own a video production company.',
    createdAt: '28/06/2001',
  },
];

function Home() {
  return (
    <div>
      <Swiper>
        {popularPosts.map((item, index) => (
          <SwiperSlide key={index}>
            <div className="block relative aspect-[21/9]">
              <img
                className="w-full aspect-[21/9] object-cover object-center"
                src={item.banner}
                alt="banner"
              />
              <div className="absolute left-0 top-0 right-0 bottom-0 bg-black/50 ">
                <div className="container mx-auto pb-24 flex h-full items-end justify-between">
                  <div className="flex-1 flex flex-col gap-y-4">
                    <p className="text-[#e5e5e5] text-xs font-light leading-5">
                      {item.createdAt}
                    </p>
                    <h1 className="text-[#f8f9fa] text-2xl font-bold leading-10 max-w-[600px]">
                      {item.title}
                    </h1>
                    <p className="text-[#e5e5e5] text-xs font-light leading-5">
                      {item.description}
                    </p>
                  </div>
                  <div>
                    {index + 1}/{popularPosts.length}
                  </div>
                </div>
              </div>
            </div>
          </SwiperSlide>
        ))}
      </Swiper>
      <div className="my-24 mx-auto container">
        <div></div>
        <div className="grid grid-cols-4 gap-x-8 gap-y-11">
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
      </div>
    </div>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>;
};

export default Home;
